apiVersion: v2
name: venafi-kubernetes-agent
type: application

description: |-
  The Discovery Agent connects your Kubernetes or OpenShift cluster to the CyberArk Certificate Manager.

maintainers:
  - name: CyberArk
    email: mis.support@cyberark.com
    url: https://www.cyberark.com

sources:
  - https://github.com/jetstack/jetstack-secure

# These versions are meant to be overridden by `make helm-chart`. No `v` prefix
# for the `version` because Helm doesn't support auto-determining the latest
# version for OCI Helm charts that use a `v` prefix.
version: 0.0.0
appVersion: "v0.0.0"
