apiVersion: v2
name: jetstack-agent
description: TLS Protect for Kubernetes Agent
type: application
version: 1.0.0
appVersion: "v1.0.0"
home: https://github.com/jetstack/jetstack-secure
maintainers:
- name: JSCP and CRE Team
  email: tls-protect-for-kubernetes@jetstack.io
  url: https://platform.jetstack.io/documentation
sources:
- https://github.com/jetstack/jetstack-secure
